### ISSUE TITLE
Sample Examples not working

### ISSUE THREAD

**Issue by bhavya-kothari** [macoscope/MCSCollectionUtility#1]
I would to congratulate for making such a good classes which can be used every now and then.
However i am getting following error in the sample code given.

![collectionerror](https://cloud.githubusercontent.com/assets/6544244/2773963/595ebe74-caab-11e3-9ee1-3d96a69e8471.png)

It would be great if you can provide more examples.

**Comment by Augustyniak** [comment]
Hey
Thanks for reporting this. I fixed that. 
There will be probably more examples in (near) the future.
